### PR TITLE
Armor Page Enhancements

### PR DESCRIPTION
**Pull request by Camburgaler**
- added button to ignore an item if you don't have access to it
- ignored items can be un-ignored if ignored by mistake
- ignored items will not show up in armor suggestions
- added data display for each resistance since some (small number of) armors have different resistances for statuses despite sharing a resistance stat (e.g. Perfumer Robe (Altered) has 63 Sleep resist and 57 Madness resist, despite both being governed by Focus)
- added the ability to sort by any absorption or resistance type
- changed the absorptions and resistances to be stored in key-value pairs instead of arrays so that it's easier to know exactly what absorption or resistance is being referenced in the code
- shaved ~400ms off the worst-case update time, making it ~250ms on average

### CODE REVIEW

**Comment by Camburgaler** [comment]
This PR was created at ~3:30 AM my time, so please forgive any silly mistakes if any were made in the code. I'll be happy to fix anything that isn't up to par.

**Comment by vodofrede** [comment]
I think it's a good idea to be able to ignore equipment, however, with the current armor optimization algorithm the site just feels too slow to do this properly, as every ignore action refreshes the list which takes about a second each. So, I would like to find a better algorithm first before merging this. I'll be able to work on a better solution next week.

Also, I think it would be good if we settled on a common auto formatter, since the code changes seem much larger currently because all the code gets formatted each time =). If you use vscode we can just use a .vscode settings folder.

**Comment by Camburgaler** [comment]
Certainly, that all makes sense to me. 

What I've noticed is that it's only the "Greatest Average Negation" and "Greatest Physical Negation" sorting options that take some time to load. The other sorting options are nearly instantaneous and, when testing locally, the updates to the page when selecting armor to ignore were similarly fast. But I agree that it would be worthwhile to look into speeding up the update method.

I also agree that a common formatter would be beneficial. I've just been using vscode's Prettier plugin and I have it configured to autoformat on save. The only adjustment I've made to the default Prettier settings is that I have the tab width set to 4 spaces. Otherwise, it's just the default plugin.

**Comment by vodofrede** [comment]
I could not get the current Promise.all(..) version to function, so I edited it slightly:
```javascript
async function init() {
    EQUIPMENT = (await Promise.all([
        fetch("/data/helmets.json").then(r => r.json()),
        fetch("/data/chestpieces.json").then(r => r.json()),
        fetch("/data/gauntlets.json").then(r => r.json()),
        fetch("/data/leggings.json").then(r => r.json()),
    ])).map(json => Object.values(json));
    [HELMETS, CHESTPIECES, GAUNTLETS, LEGGINGS] = EQUIPMENT;
    
    ...
}
```

**Comment by vodofrede** [comment]
Also, I am working on a faster solution to armor optimization, but it's taking some time. Apologies!

**Comment by vodofrede** [comment]
It's a variation of the knapsack problem, which means there should be a good solution somewhere.

**Comment by Camburgaler** [comment]
Testing locally, I've got the slowest sorting criteria (Greatest Average Absorption) down to about a quarter of a second per update without any changes to the knapsack method. If you can optimize knapsack substantially, we'll be in a great place, performance-wise.
palmoe_armor

**Comment by Camburgaler** [comment]
@vodofrede If you would like, we can close this PR and focus instead on [the other one](https://github.com/vodofrede/erdtree/pull/7), then reintroduce these changes afterward. It just depends on how you feel about the other MR. I understand it's something of a radical change, but I'd be glad to answer any questions you may have.

**Pull request closed without merging**
